version: "3"
services:
  sportsstore:
    build: .
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - sqlserver2
  sqlserver2:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "EWcuvbb!123"
      ACCEPT_EULA: "Y"